### ISSUE TITLE
Incorrect case insensitivity in makedoc.g

### ISSUE THREAD

**Issue by narc-Ontakac2** [gap-packages/congruence#9]
pos := PositionSublist(location,LowercaseString(pkgname));
should be replaced with
      pos := PositionSublist(LowercaseString(location),LowercaseString(pkgname));

Otherwise the comparision fails if the location does not contain a lower case package name (Congruence).

**Comment by olexandr-konovalov** [comment]
Thanks, agree that this makes sense, @narc-Ontakac2.
